version: "3.8"

services:
    sispak-dkph:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: sispak-dkph
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - sispak-dkph_network

    webserver:
        image: nginx:alpine
        container_name: sispak-dkph_webserver
        restart: unless-stopped
        ports:
            - "8082:80"
        volumes:
            - .:/var/www
            - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - sispak-dkph_network
        depends_on:
            - sispak-dkph

networks:
    sispak-dkph_network:
        driver: bridge
